# Generated by Django 4.2.5 on 2023-09-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_alter_source_id_alter_userincome_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Sources'},
        ),
    ]
