# Generated by Django 4.2.5 on 2023-09-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0003_alter_source_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
    ]
